import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Amburana",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="pt-br">
      <body className={`${geistSans.variable} ${geistMono.variable}`} style={{
        backgroundColor:"#032A0D",
        display: "flex",
        flexDirection: "column",
      }}>
        {children}
      </body>
    </html>
  );
}
